/* empty css                      */import{a as w,i as p,S}from"./assets/vendor-Db2TdIkw.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const v="44728966-7765244b057c0982fa05c31d9",q="https://pixabay.com/api/";async function h(e,o){try{return(await w.get(q,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch(n){throw console.error("Error fetching images:",n),n}}let a;function g(e){const o=document.querySelector(".gallery");if(!o)return;const n=e.map(r=>`
      <li class="image-container">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
        </a>
        <div class="info-bar">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </li>`).join("");o.insertAdjacentHTML("beforeend",n),a==null||a.refresh()}function P(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function b(){var e;(e=document.querySelector(".loader-wrap"))==null||e.classList.remove("disabled")}function L(){var e;(e=document.querySelector(".loader-wrap"))==null||e.classList.add("disabled")}function $(){var e;(e=document.querySelector(".load-more-btn"))==null||e.classList.remove("hidden")}function f(){var e;(e=document.querySelector(".load-more-btn"))==null||e.classList.add("hidden")}function E(e){p.success({message:e,position:"topRight"})}function c(e){p.error({message:e,position:"topRight"})}function I(){a||(a=new S(".gallery a",{captionsData:"alt",captionDelay:250}))}function O(){a==null||a.refresh()}let i=1,y="",m=0;const u=document.querySelector(".search-form"),d=document.querySelector(".load-more-btn");u==null||u.addEventListener("submit",async e=>{e.preventDefault();const o=e.target.elements.searchQuery.value.trim();if(o){y=o,i=1,P(),f();try{b();const{hits:n,totalHits:r}=await h(y,i);if(m=r,n.length===0){c("No images found. Try again.");return}g(n),E(`Hooray! We found ${r} images.`),I(),i*15>=m?(f(),c("We're sorry, but you've reached the end of search results.")):$()}catch{c("Something went wrong. Please try again.")}finally{L()}}});d==null||d.addEventListener("click",async()=>{i+=1;try{b();const{hits:e}=await h(y,i);g(e),O(),A(),i*15>=m&&(f(),c("We're sorry, but you've reached the end of search results."))}catch{c("Failed to load more images.")}finally{L()}});function A(){const e=document.querySelector(".gallery .photo-card:last-child");e&&e.scrollIntoView({behavior:"smooth",block:"start"})}
//# sourceMappingURL=index.js.map
